/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GenericValue = IDL.Rec();
export const Value = IDL.Rec();
export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AudiusTrack = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'artworkUrl' : IDL.Text,
  'streamUrl' : IDL.Text,
  'artist' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BuyNFTResponse = IDL.Variant({
  'ok' : IDL.Null,
  'cannotBuyOwn' : IDL.Null,
  'notListed' : IDL.Null,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const AlbumTier = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'supply' : IDL.Nat,
  'price' : IDL.Nat,
});
export const AlbumInput = IDL.Record({
  'id' : IDL.Text,
  'theme' : IDL.Text,
  'listenerTier' : AlbumTier,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'collectorTier' : AlbumTier,
  'investorTier' : AlbumTier,
});
export const AlbumView = IDL.Record({
  'id' : IDL.Text,
  'theme' : IDL.Text,
  'listenerTier' : AlbumTier,
  'creationTimestamp' : IDL.Int,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'collectorTier' : AlbumTier,
  'trackIds' : IDL.Vec(IDL.Text),
  'investorTier' : AlbumTier,
});
export const PlaylistView = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'creationTimestamp' : IDL.Int,
  'trackIds' : IDL.Vec(IDL.Text),
  'audiusTracks' : IDL.Vec(AudiusTrack),
});
export const TransferNFTResponse = IDL.Variant({
  'ok' : IDL.Null,
  'alreadyListed' : IDL.Null,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const Dip721CollectionMetadata = IDL.Record({
  'logo' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'totalSupply' : IDL.Nat,
  'created_at' : IDL.Nat64,
  'upgraded_at' : IDL.Nat64,
  'symbol' : IDL.Opt(IDL.Text),
});
GenericValue.fill(
  IDL.Variant({
    'Nat64Content' : IDL.Nat64,
    'Nat32Content' : IDL.Nat32,
    'BoolContent' : IDL.Bool,
    'Nat8Content' : IDL.Nat8,
    'Int64Content' : IDL.Int64,
    'IntContent' : IDL.Int,
    'NatContent' : IDL.Nat,
    'Nat16Content' : IDL.Nat16,
    'Int32Content' : IDL.Int32,
    'Int8Content' : IDL.Int8,
    'FloatContent' : IDL.Float64,
    'Int16Content' : IDL.Int16,
    'BlobContent' : IDL.Vec(IDL.Nat8),
    'NestedContent' : IDL.Vec(IDL.Tuple(IDL.Text, GenericValue)),
    'Principal' : IDL.Principal,
    'TextContent' : IDL.Text,
  })
);
export const TokenMetadata = IDL.Record({
  'transferred_at' : IDL.Opt(IDL.Nat64),
  'transferred_by' : IDL.Opt(IDL.Principal),
  'owner' : IDL.Opt(IDL.Principal),
  'operator' : IDL.Opt(IDL.Principal),
  'approved_at' : IDL.Opt(IDL.Nat64),
  'approved_by' : IDL.Opt(IDL.Principal),
  'properties' : IDL.Vec(IDL.Tuple(IDL.Text, GenericValue)),
  'is_burned' : IDL.Bool,
  'token_identifier' : IDL.Nat,
  'burned_at' : IDL.Opt(IDL.Nat64),
  'burned_by' : IDL.Opt(IDL.Principal),
  'minted_at' : IDL.Nat64,
  'minted_by' : IDL.Principal,
});
export const Dip721TokenMetadataResult = IDL.Variant({
  'Ok' : TokenMetadata,
  'Err' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Genre = IDL.Variant({
  'pop' : IDL.Null,
  'other' : IDL.Text,
  'jazz' : IDL.Null,
  'rock' : IDL.Null,
  'hipHop' : IDL.Null,
  'electronic' : IDL.Null,
  'classical' : IDL.Null,
});
export const AudioFile = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Text,
  'duration' : IDL.Nat,
  'owner' : IDL.Opt(IDL.Principal),
  'blob' : ExternalBlob,
  'size' : IDL.Nat,
  'uploadTimestamp' : IDL.Int,
  'coverImage' : IDL.Opt(ExternalBlob),
  'genre' : Genre,
  'albumId' : IDL.Opt(IDL.Text),
  'isPublic' : IDL.Bool,
});
export const FileType = IDL.Variant({
  'audio' : IDL.Null,
  'combined' : IDL.Null,
  'image' : IDL.Null,
});
export const NFTMetadata = IDL.Record({
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'fileType' : FileType,
  'originalContentId' : IDL.Text,
  'mintTimestamp' : IDL.Int,
  'artist' : IDL.Text,
});
export const NFTRecord = IDL.Record({
  'imageBlob' : IDL.Opt(ExternalBlob),
  'metadata' : NFTMetadata,
  'audioBlob' : IDL.Opt(ExternalBlob),
});
export const NFTAttachmentRecord = IDL.Record({
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'mimeType' : IDL.Text,
  'isPrivate' : IDL.Bool,
});
export const StableCoin = IDL.Variant({
  'tusd' : IDL.Null,
  'usdc' : IDL.Null,
  'usde' : IDL.Null,
  'usdp' : IDL.Null,
  'rlusd' : IDL.Null,
});
export const RevenueSplit = IDL.Record({
  'address' : IDL.Principal,
  'percentage' : IDL.Nat,
});
export const NFTParameters = IDL.Record({
  'stableCoin' : StableCoin,
  'revenueSplits' : IDL.Vec(RevenueSplit),
  'price' : IDL.Nat,
  'royaltyPercentage' : IDL.Nat,
});
export const NFTRecordWithParamsView = IDL.Record({
  'tokenId' : IDL.Nat,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'metadata' : NFTMetadata,
  'audioBlob' : IDL.Opt(ExternalBlob),
  'attachments' : IDL.Vec(NFTAttachmentRecord),
  'params' : NFTParameters,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const NFTListing = IDL.Record({
  'title' : IDL.Text,
  'tokenId' : IDL.Nat,
  'listedAt' : IDL.Int,
  'description' : IDL.Text,
  'fileType' : FileType,
  'seller' : IDL.Principal,
  'priceE8s' : IDL.Nat,
});
export const Account = IDL.Record({
  'owner' : IDL.Principal,
  'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
Value.fill(
  IDL.Variant({
    'Int' : IDL.Int,
    'Map' : IDL.Vec(IDL.Tuple(IDL.Text, Value)),
    'Nat' : IDL.Nat,
    'Blob' : IDL.Vec(IDL.Nat8),
    'Text' : IDL.Text,
    'Array' : IDL.Vec(Value),
  })
);
export const TransferArg = IDL.Record({
  'to' : Account,
  'token_id' : IDL.Nat,
  'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'from_subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'created_at_time' : IDL.Opt(IDL.Nat64),
});
export const TransferError = IDL.Variant({
  'GenericError' : IDL.Record({ 'message' : IDL.Text, 'error_code' : IDL.Nat }),
  'Duplicate' : IDL.Record({ 'duplicate_of' : IDL.Nat }),
  'NonExistingTokenId' : IDL.Null,
  'Unauthorized' : IDL.Null,
  'CreatedInFuture' : IDL.Record({ 'ledger_time' : IDL.Nat64 }),
  'InvalidRecipient' : IDL.Null,
  'GenericBatchError' : IDL.Record({
    'message' : IDL.Text,
    'error_code' : IDL.Nat,
  }),
  'TooOld' : IDL.Null,
});
export const TransferResult = IDL.Variant({
  'Ok' : IDL.Nat,
  'Err' : TransferError,
});
export const ListNFTResponse = IDL.Variant({
  'ok' : IDL.Null,
  'alreadyListed' : IDL.Null,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const MintNFTRequest = IDL.Record({
  'title' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'audioBlob' : IDL.Opt(ExternalBlob),
  'fileType' : FileType,
  'originalContentId' : IDL.Opt(IDL.Text),
  'artist' : IDL.Text,
});
export const MintNFTResponse = IDL.Variant({
  'ok' : IDL.Nat,
  'invalidInput' : IDL.Text,
  'unauthorized' : IDL.Null,
});
export const MintNFTWithParamsRequest = IDL.Record({
  'title' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'audioBlob' : IDL.Opt(ExternalBlob),
  'fileType' : FileType,
  'originalContentId' : IDL.Opt(IDL.Text),
  'artist' : IDL.Text,
  'attachments' : IDL.Vec(NFTAttachmentRecord),
  'params' : NFTParameters,
});
export const SupportedStandard = IDL.Record({
  'url' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAudiusTrackToPlaylist' : IDL.Func([IDL.Text, AudiusTrack], [], []),
  'addTrackToAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addTrackToPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyNFT' : IDL.Func([IDL.Nat], [BuyNFTResponse], []),
  'createAlbum' : IDL.Func([AlbumInput], [AlbumView], []),
  'createPlaylist' : IDL.Func([IDL.Text, IDL.Text], [PlaylistView], []),
  'deleteAlbum' : IDL.Func([IDL.Text], [], []),
  'deleteAudioFile' : IDL.Func([IDL.Text], [], []),
  'deletePlaylist' : IDL.Func([IDL.Text], [], []),
  'delistNFT' : IDL.Func([IDL.Nat], [TransferNFTResponse], []),
  'dip721_metadata' : IDL.Func([], [Dip721CollectionMetadata], ['query']),
  'dip721_name' : IDL.Func([], [IDL.Text], ['query']),
  'dip721_owner_token_identifiers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'dip721_symbol' : IDL.Func([], [IDL.Text], ['query']),
  'dip721_token_metadata' : IDL.Func(
      [IDL.Nat],
      [Dip721TokenMetadataResult],
      ['query'],
    ),
  'dip721_total_supply' : IDL.Func([], [IDL.Nat], ['query']),
  'getAlbum' : IDL.Func([IDL.Text], [IDL.Opt(AlbumView)], ['query']),
  'getAllAudioFiles' : IDL.Func([], [IDL.Vec(AudioFile)], ['query']),
  'getAllNFTRecords' : IDL.Func([], [IDL.Vec(NFTRecord)], ['query']),
  'getAllNFTRecordsWithParams' : IDL.Func(
      [],
      [IDL.Vec(NFTRecordWithParamsView)],
      ['query'],
    ),
  'getAllPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
  'getAudioFile' : IDL.Func([IDL.Text], [IDL.Opt(AudioFile)], ['query']),
  'getAudioFilesByAlbum' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AudioFile)],
      ['query'],
    ),
  'getCallerAudioFiles' : IDL.Func([], [IDL.Vec(AudioFile)], ['query']),
  'getCallerNFTRecordsWithParams' : IDL.Func(
      [],
      [IDL.Vec(NFTRecordWithParamsView)],
      ['query'],
    ),
  'getCallerPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterId' : IDL.Func([], [IDL.Principal], ['query']),
  'getListings' : IDL.Func([], [IDL.Vec(NFTListing)], ['query']),
  'getNFTRecord' : IDL.Func([IDL.Nat], [IDL.Opt(NFTRecord)], ['query']),
  'getNFTRecordWithParams' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(NFTRecordWithParamsView)],
      ['query'],
    ),
  'getPlaylist' : IDL.Func([IDL.Text], [IDL.Opt(PlaylistView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'icrc7_balance_of' : IDL.Func(
      [IDL.Vec(Account)],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'icrc7_collection_metadata' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Value))],
      ['query'],
    ),
  'icrc7_name' : IDL.Func([], [IDL.Text], ['query']),
  'icrc7_owner_of' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(IDL.Opt(Account))],
      ['query'],
    ),
  'icrc7_symbol' : IDL.Func([], [IDL.Text], ['query']),
  'icrc7_tokens_of' : IDL.Func(
      [Account, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'icrc7_total_supply' : IDL.Func([], [IDL.Nat], ['query']),
  'icrc7_transfer' : IDL.Func(
      [IDL.Vec(TransferArg)],
      [IDL.Vec(IDL.Opt(TransferResult))],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAlbums' : IDL.Func([], [IDL.Vec(AlbumView)], ['query']),
  'listNFTForSale' : IDL.Func([IDL.Nat, IDL.Nat], [ListNFTResponse], []),
  'mintNFT' : IDL.Func([MintNFTRequest], [MintNFTResponse], []),
  'mintNFTwithParams' : IDL.Func(
      [MintNFTWithParamsRequest],
      [MintNFTResponse],
      [],
    ),
  'ownerOf' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Principal)], ['query']),
  'removeAudiusTrackFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeTrackFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'supportedStandards' : IDL.Func([], [IDL.Vec(SupportedStandard)], ['query']),
  'transferNFT' : IDL.Func([IDL.Nat, IDL.Principal], [TransferNFTResponse], []),
  'updateAlbum' : IDL.Func([IDL.Text, AlbumInput], [AlbumView], []),
  'updatePlaylistTitle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTrackCoverImage' : IDL.Func(
      [IDL.Text, ExternalBlob],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'uploadAudioFile' : IDL.Func([AudioFile], [IDL.Text], []),
  'uploadTrackWithAlbum' : IDL.Func(
      [AudioFile, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GenericValue = IDL.Rec();
  const Value = IDL.Rec();
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AudiusTrack = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'artworkUrl' : IDL.Text,
    'streamUrl' : IDL.Text,
    'artist' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BuyNFTResponse = IDL.Variant({
    'ok' : IDL.Null,
    'cannotBuyOwn' : IDL.Null,
    'notListed' : IDL.Null,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const AlbumTier = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'supply' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const AlbumInput = IDL.Record({
    'id' : IDL.Text,
    'theme' : IDL.Text,
    'listenerTier' : AlbumTier,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'collectorTier' : AlbumTier,
    'investorTier' : AlbumTier,
  });
  const AlbumView = IDL.Record({
    'id' : IDL.Text,
    'theme' : IDL.Text,
    'listenerTier' : AlbumTier,
    'creationTimestamp' : IDL.Int,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'collectorTier' : AlbumTier,
    'trackIds' : IDL.Vec(IDL.Text),
    'investorTier' : AlbumTier,
  });
  const PlaylistView = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'creationTimestamp' : IDL.Int,
    'trackIds' : IDL.Vec(IDL.Text),
    'audiusTracks' : IDL.Vec(AudiusTrack),
  });
  const TransferNFTResponse = IDL.Variant({
    'ok' : IDL.Null,
    'alreadyListed' : IDL.Null,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const Dip721CollectionMetadata = IDL.Record({
    'logo' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'totalSupply' : IDL.Nat,
    'created_at' : IDL.Nat64,
    'upgraded_at' : IDL.Nat64,
    'symbol' : IDL.Opt(IDL.Text),
  });
  GenericValue.fill(
    IDL.Variant({
      'Nat64Content' : IDL.Nat64,
      'Nat32Content' : IDL.Nat32,
      'BoolContent' : IDL.Bool,
      'Nat8Content' : IDL.Nat8,
      'Int64Content' : IDL.Int64,
      'IntContent' : IDL.Int,
      'NatContent' : IDL.Nat,
      'Nat16Content' : IDL.Nat16,
      'Int32Content' : IDL.Int32,
      'Int8Content' : IDL.Int8,
      'FloatContent' : IDL.Float64,
      'Int16Content' : IDL.Int16,
      'BlobContent' : IDL.Vec(IDL.Nat8),
      'NestedContent' : IDL.Vec(IDL.Tuple(IDL.Text, GenericValue)),
      'Principal' : IDL.Principal,
      'TextContent' : IDL.Text,
    })
  );
  const TokenMetadata = IDL.Record({
    'transferred_at' : IDL.Opt(IDL.Nat64),
    'transferred_by' : IDL.Opt(IDL.Principal),
    'owner' : IDL.Opt(IDL.Principal),
    'operator' : IDL.Opt(IDL.Principal),
    'approved_at' : IDL.Opt(IDL.Nat64),
    'approved_by' : IDL.Opt(IDL.Principal),
    'properties' : IDL.Vec(IDL.Tuple(IDL.Text, GenericValue)),
    'is_burned' : IDL.Bool,
    'token_identifier' : IDL.Nat,
    'burned_at' : IDL.Opt(IDL.Nat64),
    'burned_by' : IDL.Opt(IDL.Principal),
    'minted_at' : IDL.Nat64,
    'minted_by' : IDL.Principal,
  });
  const Dip721TokenMetadataResult = IDL.Variant({
    'Ok' : TokenMetadata,
    'Err' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Genre = IDL.Variant({
    'pop' : IDL.Null,
    'other' : IDL.Text,
    'jazz' : IDL.Null,
    'rock' : IDL.Null,
    'hipHop' : IDL.Null,
    'electronic' : IDL.Null,
    'classical' : IDL.Null,
  });
  const AudioFile = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Text,
    'duration' : IDL.Nat,
    'owner' : IDL.Opt(IDL.Principal),
    'blob' : ExternalBlob,
    'size' : IDL.Nat,
    'uploadTimestamp' : IDL.Int,
    'coverImage' : IDL.Opt(ExternalBlob),
    'genre' : Genre,
    'albumId' : IDL.Opt(IDL.Text),
    'isPublic' : IDL.Bool,
  });
  const FileType = IDL.Variant({
    'audio' : IDL.Null,
    'combined' : IDL.Null,
    'image' : IDL.Null,
  });
  const NFTMetadata = IDL.Record({
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'fileType' : FileType,
    'originalContentId' : IDL.Text,
    'mintTimestamp' : IDL.Int,
    'artist' : IDL.Text,
  });
  const NFTRecord = IDL.Record({
    'imageBlob' : IDL.Opt(ExternalBlob),
    'metadata' : NFTMetadata,
    'audioBlob' : IDL.Opt(ExternalBlob),
  });
  const NFTAttachmentRecord = IDL.Record({
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'mimeType' : IDL.Text,
    'isPrivate' : IDL.Bool,
  });
  const StableCoin = IDL.Variant({
    'tusd' : IDL.Null,
    'usdc' : IDL.Null,
    'usde' : IDL.Null,
    'usdp' : IDL.Null,
    'rlusd' : IDL.Null,
  });
  const RevenueSplit = IDL.Record({
    'address' : IDL.Principal,
    'percentage' : IDL.Nat,
  });
  const NFTParameters = IDL.Record({
    'stableCoin' : StableCoin,
    'revenueSplits' : IDL.Vec(RevenueSplit),
    'price' : IDL.Nat,
    'royaltyPercentage' : IDL.Nat,
  });
  const NFTRecordWithParamsView = IDL.Record({
    'tokenId' : IDL.Nat,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'metadata' : NFTMetadata,
    'audioBlob' : IDL.Opt(ExternalBlob),
    'attachments' : IDL.Vec(NFTAttachmentRecord),
    'params' : NFTParameters,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const NFTListing = IDL.Record({
    'title' : IDL.Text,
    'tokenId' : IDL.Nat,
    'listedAt' : IDL.Int,
    'description' : IDL.Text,
    'fileType' : FileType,
    'seller' : IDL.Principal,
    'priceE8s' : IDL.Nat,
  });
  const Account = IDL.Record({
    'owner' : IDL.Principal,
    'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  Value.fill(
    IDL.Variant({
      'Int' : IDL.Int,
      'Map' : IDL.Vec(IDL.Tuple(IDL.Text, Value)),
      'Nat' : IDL.Nat,
      'Blob' : IDL.Vec(IDL.Nat8),
      'Text' : IDL.Text,
      'Array' : IDL.Vec(Value),
    })
  );
  const TransferArg = IDL.Record({
    'to' : Account,
    'token_id' : IDL.Nat,
    'memo' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'from_subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'created_at_time' : IDL.Opt(IDL.Nat64),
  });
  const TransferError = IDL.Variant({
    'GenericError' : IDL.Record({
      'message' : IDL.Text,
      'error_code' : IDL.Nat,
    }),
    'Duplicate' : IDL.Record({ 'duplicate_of' : IDL.Nat }),
    'NonExistingTokenId' : IDL.Null,
    'Unauthorized' : IDL.Null,
    'CreatedInFuture' : IDL.Record({ 'ledger_time' : IDL.Nat64 }),
    'InvalidRecipient' : IDL.Null,
    'GenericBatchError' : IDL.Record({
      'message' : IDL.Text,
      'error_code' : IDL.Nat,
    }),
    'TooOld' : IDL.Null,
  });
  const TransferResult = IDL.Variant({ 'Ok' : IDL.Nat, 'Err' : TransferError });
  const ListNFTResponse = IDL.Variant({
    'ok' : IDL.Null,
    'alreadyListed' : IDL.Null,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const MintNFTRequest = IDL.Record({
    'title' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'audioBlob' : IDL.Opt(ExternalBlob),
    'fileType' : FileType,
    'originalContentId' : IDL.Opt(IDL.Text),
    'artist' : IDL.Text,
  });
  const MintNFTResponse = IDL.Variant({
    'ok' : IDL.Nat,
    'invalidInput' : IDL.Text,
    'unauthorized' : IDL.Null,
  });
  const MintNFTWithParamsRequest = IDL.Record({
    'title' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'audioBlob' : IDL.Opt(ExternalBlob),
    'fileType' : FileType,
    'originalContentId' : IDL.Opt(IDL.Text),
    'artist' : IDL.Text,
    'attachments' : IDL.Vec(NFTAttachmentRecord),
    'params' : NFTParameters,
  });
  const SupportedStandard = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAudiusTrackToPlaylist' : IDL.Func([IDL.Text, AudiusTrack], [], []),
    'addTrackToAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addTrackToPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyNFT' : IDL.Func([IDL.Nat], [BuyNFTResponse], []),
    'createAlbum' : IDL.Func([AlbumInput], [AlbumView], []),
    'createPlaylist' : IDL.Func([IDL.Text, IDL.Text], [PlaylistView], []),
    'deleteAlbum' : IDL.Func([IDL.Text], [], []),
    'deleteAudioFile' : IDL.Func([IDL.Text], [], []),
    'deletePlaylist' : IDL.Func([IDL.Text], [], []),
    'delistNFT' : IDL.Func([IDL.Nat], [TransferNFTResponse], []),
    'dip721_metadata' : IDL.Func([], [Dip721CollectionMetadata], ['query']),
    'dip721_name' : IDL.Func([], [IDL.Text], ['query']),
    'dip721_owner_token_identifiers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'dip721_symbol' : IDL.Func([], [IDL.Text], ['query']),
    'dip721_token_metadata' : IDL.Func(
        [IDL.Nat],
        [Dip721TokenMetadataResult],
        ['query'],
      ),
    'dip721_total_supply' : IDL.Func([], [IDL.Nat], ['query']),
    'getAlbum' : IDL.Func([IDL.Text], [IDL.Opt(AlbumView)], ['query']),
    'getAllAudioFiles' : IDL.Func([], [IDL.Vec(AudioFile)], ['query']),
    'getAllNFTRecords' : IDL.Func([], [IDL.Vec(NFTRecord)], ['query']),
    'getAllNFTRecordsWithParams' : IDL.Func(
        [],
        [IDL.Vec(NFTRecordWithParamsView)],
        ['query'],
      ),
    'getAllPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
    'getAudioFile' : IDL.Func([IDL.Text], [IDL.Opt(AudioFile)], ['query']),
    'getAudioFilesByAlbum' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AudioFile)],
        ['query'],
      ),
    'getCallerAudioFiles' : IDL.Func([], [IDL.Vec(AudioFile)], ['query']),
    'getCallerNFTRecordsWithParams' : IDL.Func(
        [],
        [IDL.Vec(NFTRecordWithParamsView)],
        ['query'],
      ),
    'getCallerPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterId' : IDL.Func([], [IDL.Principal], ['query']),
    'getListings' : IDL.Func([], [IDL.Vec(NFTListing)], ['query']),
    'getNFTRecord' : IDL.Func([IDL.Nat], [IDL.Opt(NFTRecord)], ['query']),
    'getNFTRecordWithParams' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(NFTRecordWithParamsView)],
        ['query'],
      ),
    'getPlaylist' : IDL.Func([IDL.Text], [IDL.Opt(PlaylistView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'icrc7_balance_of' : IDL.Func(
        [IDL.Vec(Account)],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'icrc7_collection_metadata' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Value))],
        ['query'],
      ),
    'icrc7_name' : IDL.Func([], [IDL.Text], ['query']),
    'icrc7_owner_of' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(IDL.Opt(Account))],
        ['query'],
      ),
    'icrc7_symbol' : IDL.Func([], [IDL.Text], ['query']),
    'icrc7_tokens_of' : IDL.Func(
        [Account, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'icrc7_total_supply' : IDL.Func([], [IDL.Nat], ['query']),
    'icrc7_transfer' : IDL.Func(
        [IDL.Vec(TransferArg)],
        [IDL.Vec(IDL.Opt(TransferResult))],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAlbums' : IDL.Func([], [IDL.Vec(AlbumView)], ['query']),
    'listNFTForSale' : IDL.Func([IDL.Nat, IDL.Nat], [ListNFTResponse], []),
    'mintNFT' : IDL.Func([MintNFTRequest], [MintNFTResponse], []),
    'mintNFTwithParams' : IDL.Func(
        [MintNFTWithParamsRequest],
        [MintNFTResponse],
        [],
      ),
    'ownerOf' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Principal)], ['query']),
    'removeAudiusTrackFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeTrackFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'supportedStandards' : IDL.Func(
        [],
        [IDL.Vec(SupportedStandard)],
        ['query'],
      ),
    'transferNFT' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [TransferNFTResponse],
        [],
      ),
    'updateAlbum' : IDL.Func([IDL.Text, AlbumInput], [AlbumView], []),
    'updatePlaylistTitle' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTrackCoverImage' : IDL.Func(
        [IDL.Text, ExternalBlob],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'uploadAudioFile' : IDL.Func([AudioFile], [IDL.Text], []),
    'uploadTrackWithAlbum' : IDL.Func(
        [AudioFile, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };