/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AudioFile {
  'id' : string,
  'title' : string,
  'creator' : string,
  'duration' : bigint,
  'owner' : [] | [Principal],
  'blob' : ExternalBlob,
  'size' : bigint,
  'uploadTimestamp' : bigint,
  'coverImage' : [] | [ExternalBlob],
  'genre' : Genre,
  'isPublic' : boolean,
}
export interface AudiusTrack {
  'id' : string,
  'title' : string,
  'artworkUrl' : string,
  'streamUrl' : string,
  'artist' : string,
}
export type ExternalBlob = Uint8Array;
export type FileType = { 'audio' : null } |
  { 'combined' : null } |
  { 'image' : null };
export type Genre = { 'pop' : null } |
  { 'other' : string } |
  { 'jazz' : null } |
  { 'rock' : null } |
  { 'hipHop' : null } |
  { 'electronic' : null } |
  { 'classical' : null };
export interface MintNFTRequest {
  'title' : string,
  'imageBlob' : [] | [ExternalBlob],
  'description' : string,
  'audioBlob' : [] | [ExternalBlob],
  'fileType' : FileType,
  'originalContentId' : [] | [string],
  'artist' : string,
}
export type MintNFTResponse = { 'ok' : bigint } |
  { 'invalidInput' : string } |
  { 'unauthorized' : null };
export interface MintNFTWithParamsRequest {
  'title' : string,
  'imageBlob' : [] | [ExternalBlob],
  'description' : string,
  'audioBlob' : [] | [ExternalBlob],
  'fileType' : FileType,
  'originalContentId' : [] | [string],
  'artist' : string,
  'params' : NFTParameters,
}
export interface NFTMetadata {
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'fileType' : FileType,
  'originalContentId' : string,
  'mintTimestamp' : bigint,
  'artist' : string,
}
export interface NFTParameters {
  'stableCoin' : StableCoin,
  'revenueSplits' : Array<RevenueSplit>,
  'price' : bigint,
  'royaltyPercentage' : bigint,
}
export interface NFTRecord {
  'imageBlob' : [] | [ExternalBlob],
  'metadata' : NFTMetadata,
  'audioBlob' : [] | [ExternalBlob],
}
export interface NFTRecordWithParams {
  'imageBlob' : [] | [ExternalBlob],
  'metadata' : NFTMetadata,
  'audioBlob' : [] | [ExternalBlob],
  'params' : NFTParameters,
}
export interface PlaylistView {
  'id' : string,
  'title' : string,
  'owner' : Principal,
  'creationTimestamp' : bigint,
  'trackIds' : Array<string>,
  'audiusTracks' : Array<AudiusTrack>,
}
export interface RevenueSplit { 'address' : Principal, 'percentage' : bigint }
export type StableCoin = { 'tusd' : null } |
  { 'usdc' : null } |
  { 'usde' : null } |
  { 'usdp' : null } |
  { 'rlusd' : null };
export interface UserProfile {
  'bio' : [] | [string],
  'name' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAudiusTrackToPlaylist' : ActorMethod<[string, AudiusTrack], undefined>,
  'addTrackToPlaylist' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPlaylist' : ActorMethod<[string, string], PlaylistView>,
  'deleteAudioFile' : ActorMethod<[string], undefined>,
  'deletePlaylist' : ActorMethod<[string], undefined>,
  'getAllAudioFiles' : ActorMethod<[], Array<AudioFile>>,
  'getAllNFTRecords' : ActorMethod<[], Array<NFTRecord>>,
  'getAllNFTRecordsWithParams' : ActorMethod<[], Array<NFTRecordWithParams>>,
  'getAllPlaylists' : ActorMethod<[], Array<PlaylistView>>,
  'getAudioFile' : ActorMethod<[string], [] | [AudioFile]>,
  'getCallerAudioFiles' : ActorMethod<[], Array<AudioFile>>,
  'getCallerNFTRecordsWithParams' : ActorMethod<[], Array<NFTRecordWithParams>>,
  'getCallerPlaylists' : ActorMethod<[], Array<PlaylistView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterId' : ActorMethod<[], Principal>,
  'getNFTRecord' : ActorMethod<[bigint], [] | [NFTRecord]>,
  'getNFTRecordWithParams' : ActorMethod<[bigint], [] | [NFTRecordWithParams]>,
  'getPlaylist' : ActorMethod<[string], [] | [PlaylistView]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'mintNFT' : ActorMethod<[MintNFTRequest], MintNFTResponse>,
  'mintNFTwithParams' : ActorMethod<
    [MintNFTWithParamsRequest],
    MintNFTResponse
  >,
  'removeAudiusTrackFromPlaylist' : ActorMethod<[string, string], undefined>,
  'removeTrackFromPlaylist' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePlaylistTitle' : ActorMethod<[string, string], undefined>,
  'uploadAudioFile' : ActorMethod<[AudioFile], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];