/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AudiusTrack = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'artworkUrl' : IDL.Text,
  'streamUrl' : IDL.Text,
  'artist' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlaylistView = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'creationTimestamp' : IDL.Int,
  'trackIds' : IDL.Vec(IDL.Text),
  'audiusTracks' : IDL.Vec(AudiusTrack),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Genre = IDL.Variant({
  'pop' : IDL.Null,
  'other' : IDL.Text,
  'jazz' : IDL.Null,
  'rock' : IDL.Null,
  'hipHop' : IDL.Null,
  'electronic' : IDL.Null,
  'classical' : IDL.Null,
});
export const AudioFile = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Text,
  'duration' : IDL.Nat,
  'owner' : IDL.Opt(IDL.Principal),
  'blob' : ExternalBlob,
  'size' : IDL.Nat,
  'uploadTimestamp' : IDL.Int,
  'coverImage' : IDL.Opt(ExternalBlob),
  'genre' : Genre,
  'isPublic' : IDL.Bool,
});
export const FileType = IDL.Variant({
  'audio' : IDL.Null,
  'combined' : IDL.Null,
  'image' : IDL.Null,
});
export const NFTMetadata = IDL.Record({
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'fileType' : FileType,
  'originalContentId' : IDL.Text,
  'mintTimestamp' : IDL.Int,
  'artist' : IDL.Text,
});
export const NFTRecord = IDL.Record({
  'imageBlob' : IDL.Opt(ExternalBlob),
  'metadata' : NFTMetadata,
  'audioBlob' : IDL.Opt(ExternalBlob),
});
export const StableCoin = IDL.Variant({
  'tusd' : IDL.Null,
  'usdc' : IDL.Null,
  'usde' : IDL.Null,
  'usdp' : IDL.Null,
  'rlusd' : IDL.Null,
});
export const RevenueSplit = IDL.Record({
  'address' : IDL.Principal,
  'percentage' : IDL.Nat,
});
export const NFTParameters = IDL.Record({
  'stableCoin' : StableCoin,
  'revenueSplits' : IDL.Vec(RevenueSplit),
  'price' : IDL.Nat,
  'royaltyPercentage' : IDL.Nat,
});
export const NFTRecordWithParams = IDL.Record({
  'imageBlob' : IDL.Opt(ExternalBlob),
  'metadata' : NFTMetadata,
  'audioBlob' : IDL.Opt(ExternalBlob),
  'params' : NFTParameters,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const MintNFTRequest = IDL.Record({
  'title' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'audioBlob' : IDL.Opt(ExternalBlob),
  'fileType' : FileType,
  'originalContentId' : IDL.Opt(IDL.Text),
  'artist' : IDL.Text,
});
export const MintNFTResponse = IDL.Variant({
  'ok' : IDL.Nat,
  'invalidInput' : IDL.Text,
  'unauthorized' : IDL.Null,
});
export const MintNFTWithParamsRequest = IDL.Record({
  'title' : IDL.Text,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'description' : IDL.Text,
  'audioBlob' : IDL.Opt(ExternalBlob),
  'fileType' : FileType,
  'originalContentId' : IDL.Opt(IDL.Text),
  'artist' : IDL.Text,
  'params' : NFTParameters,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAudiusTrackToPlaylist' : IDL.Func([IDL.Text, AudiusTrack], [], []),
  'addTrackToPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPlaylist' : IDL.Func([IDL.Text, IDL.Text], [PlaylistView], []),
  'deleteAudioFile' : IDL.Func([IDL.Text], [], []),
  'deletePlaylist' : IDL.Func([IDL.Text], [], []),
  'getAllAudioFiles' : IDL.Func([], [IDL.Vec(AudioFile)], ['query']),
  'getAllNFTRecords' : IDL.Func([], [IDL.Vec(NFTRecord)], ['query']),
  'getAllNFTRecordsWithParams' : IDL.Func(
      [],
      [IDL.Vec(NFTRecordWithParams)],
      ['query'],
    ),
  'getAllPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
  'getAudioFile' : IDL.Func([IDL.Text], [IDL.Opt(AudioFile)], ['query']),
  'getCallerAudioFiles' : IDL.Func([], [IDL.Vec(AudioFile)], ['query']),
  'getCallerNFTRecordsWithParams' : IDL.Func(
      [],
      [IDL.Vec(NFTRecordWithParams)],
      ['query'],
    ),
  'getCallerPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterId' : IDL.Func([], [IDL.Principal], ['query']),
  'getNFTRecord' : IDL.Func([IDL.Nat], [IDL.Opt(NFTRecord)], ['query']),
  'getNFTRecordWithParams' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(NFTRecordWithParams)],
      ['query'],
    ),
  'getPlaylist' : IDL.Func([IDL.Text], [IDL.Opt(PlaylistView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'mintNFT' : IDL.Func([MintNFTRequest], [MintNFTResponse], []),
  'mintNFTwithParams' : IDL.Func(
      [MintNFTWithParamsRequest],
      [MintNFTResponse],
      [],
    ),
  'removeAudiusTrackFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeTrackFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePlaylistTitle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadAudioFile' : IDL.Func([AudioFile], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AudiusTrack = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'artworkUrl' : IDL.Text,
    'streamUrl' : IDL.Text,
    'artist' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlaylistView = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'creationTimestamp' : IDL.Int,
    'trackIds' : IDL.Vec(IDL.Text),
    'audiusTracks' : IDL.Vec(AudiusTrack),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Genre = IDL.Variant({
    'pop' : IDL.Null,
    'other' : IDL.Text,
    'jazz' : IDL.Null,
    'rock' : IDL.Null,
    'hipHop' : IDL.Null,
    'electronic' : IDL.Null,
    'classical' : IDL.Null,
  });
  const AudioFile = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Text,
    'duration' : IDL.Nat,
    'owner' : IDL.Opt(IDL.Principal),
    'blob' : ExternalBlob,
    'size' : IDL.Nat,
    'uploadTimestamp' : IDL.Int,
    'coverImage' : IDL.Opt(ExternalBlob),
    'genre' : Genre,
    'isPublic' : IDL.Bool,
  });
  const FileType = IDL.Variant({
    'audio' : IDL.Null,
    'combined' : IDL.Null,
    'image' : IDL.Null,
  });
  const NFTMetadata = IDL.Record({
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'fileType' : FileType,
    'originalContentId' : IDL.Text,
    'mintTimestamp' : IDL.Int,
    'artist' : IDL.Text,
  });
  const NFTRecord = IDL.Record({
    'imageBlob' : IDL.Opt(ExternalBlob),
    'metadata' : NFTMetadata,
    'audioBlob' : IDL.Opt(ExternalBlob),
  });
  const StableCoin = IDL.Variant({
    'tusd' : IDL.Null,
    'usdc' : IDL.Null,
    'usde' : IDL.Null,
    'usdp' : IDL.Null,
    'rlusd' : IDL.Null,
  });
  const RevenueSplit = IDL.Record({
    'address' : IDL.Principal,
    'percentage' : IDL.Nat,
  });
  const NFTParameters = IDL.Record({
    'stableCoin' : StableCoin,
    'revenueSplits' : IDL.Vec(RevenueSplit),
    'price' : IDL.Nat,
    'royaltyPercentage' : IDL.Nat,
  });
  const NFTRecordWithParams = IDL.Record({
    'imageBlob' : IDL.Opt(ExternalBlob),
    'metadata' : NFTMetadata,
    'audioBlob' : IDL.Opt(ExternalBlob),
    'params' : NFTParameters,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const MintNFTRequest = IDL.Record({
    'title' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'audioBlob' : IDL.Opt(ExternalBlob),
    'fileType' : FileType,
    'originalContentId' : IDL.Opt(IDL.Text),
    'artist' : IDL.Text,
  });
  const MintNFTResponse = IDL.Variant({
    'ok' : IDL.Nat,
    'invalidInput' : IDL.Text,
    'unauthorized' : IDL.Null,
  });
  const MintNFTWithParamsRequest = IDL.Record({
    'title' : IDL.Text,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'description' : IDL.Text,
    'audioBlob' : IDL.Opt(ExternalBlob),
    'fileType' : FileType,
    'originalContentId' : IDL.Opt(IDL.Text),
    'artist' : IDL.Text,
    'params' : NFTParameters,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAudiusTrackToPlaylist' : IDL.Func([IDL.Text, AudiusTrack], [], []),
    'addTrackToPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPlaylist' : IDL.Func([IDL.Text, IDL.Text], [PlaylistView], []),
    'deleteAudioFile' : IDL.Func([IDL.Text], [], []),
    'deletePlaylist' : IDL.Func([IDL.Text], [], []),
    'getAllAudioFiles' : IDL.Func([], [IDL.Vec(AudioFile)], ['query']),
    'getAllNFTRecords' : IDL.Func([], [IDL.Vec(NFTRecord)], ['query']),
    'getAllNFTRecordsWithParams' : IDL.Func(
        [],
        [IDL.Vec(NFTRecordWithParams)],
        ['query'],
      ),
    'getAllPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
    'getAudioFile' : IDL.Func([IDL.Text], [IDL.Opt(AudioFile)], ['query']),
    'getCallerAudioFiles' : IDL.Func([], [IDL.Vec(AudioFile)], ['query']),
    'getCallerNFTRecordsWithParams' : IDL.Func(
        [],
        [IDL.Vec(NFTRecordWithParams)],
        ['query'],
      ),
    'getCallerPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterId' : IDL.Func([], [IDL.Principal], ['query']),
    'getNFTRecord' : IDL.Func([IDL.Nat], [IDL.Opt(NFTRecord)], ['query']),
    'getNFTRecordWithParams' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(NFTRecordWithParams)],
        ['query'],
      ),
    'getPlaylist' : IDL.Func([IDL.Text], [IDL.Opt(PlaylistView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'mintNFT' : IDL.Func([MintNFTRequest], [MintNFTResponse], []),
    'mintNFTwithParams' : IDL.Func(
        [MintNFTWithParamsRequest],
        [MintNFTResponse],
        [],
      ),
    'removeAudiusTrackFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeTrackFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePlaylistTitle' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadAudioFile' : IDL.Func([AudioFile], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };