/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PlaylistView {
    id: string;
    title: string;
    owner: Principal;
    creationTimestamp: bigint;
    trackIds: Array<string>;
    audiusTracks: Array<AudiusTrack>;
}
export interface AlbumView {
    id: string;
    theme: string;
    listenerTier: AlbumTier;
    creationTimestamp: bigint;
    name: string;
    description: string;
    collectorTier: AlbumTier;
    trackIds: Array<string>;
    investorTier: AlbumTier;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface NFTRecordWithParams {
    imageBlob?: ExternalBlob;
    metadata: NFTMetadata;
    audioBlob?: ExternalBlob;
    params: NFTParameters;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Genre = {
    __kind__: "pop";
    pop: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "jazz";
    jazz: null;
} | {
    __kind__: "rock";
    rock: null;
} | {
    __kind__: "hipHop";
    hipHop: null;
} | {
    __kind__: "electronic";
    electronic: null;
} | {
    __kind__: "classical";
    classical: null;
};
export interface AudioFile {
    id: string;
    title: string;
    creator: string;
    duration: bigint;
    owner?: Principal;
    blob: ExternalBlob;
    size: bigint;
    uploadTimestamp: bigint;
    coverImage?: ExternalBlob;
    genre: Genre;
    albumId?: string;
    isPublic: boolean;
}
export interface NFTRecord {
    imageBlob?: ExternalBlob;
    metadata: NFTMetadata;
    audioBlob?: ExternalBlob;
}
export interface MintNFTRequest {
    title: string;
    imageBlob?: ExternalBlob;
    description: string;
    audioBlob?: ExternalBlob;
    fileType: FileType;
    originalContentId?: string;
    artist: string;
}
export type MintNFTResponse = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
};
export interface AudiusTrack {
    id: string;
    title: string;
    artworkUrl: string;
    streamUrl: string;
    artist: string;
}
export interface AlbumTier {
    name: string;
    description: string;
    supply: bigint;
    price: bigint;
}
export interface MintNFTWithParamsRequest {
    title: string;
    imageBlob?: ExternalBlob;
    description: string;
    audioBlob?: ExternalBlob;
    fileType: FileType;
    originalContentId?: string;
    artist: string;
    params: NFTParameters;
}
export interface NFTMetadata {
    title: string;
    owner: Principal;
    description: string;
    fileType: FileType;
    originalContentId: string;
    mintTimestamp: bigint;
    artist: string;
}
export interface AlbumInput {
    id: string;
    theme: string;
    listenerTier: AlbumTier;
    name: string;
    description: string;
    collectorTier: AlbumTier;
    investorTier: AlbumTier;
}
export interface RevenueSplit {
    address: Principal;
    percentage: bigint;
}
export interface NFTParameters {
    stableCoin: StableCoin;
    revenueSplits: Array<RevenueSplit>;
    price: bigint;
    royaltyPercentage: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    bio?: string;
    name: string;
    email?: string;
}
export enum FileType {
    audio = "audio",
    combined = "combined",
    image = "image"
}
export enum StableCoin {
    tusd = "tusd",
    usdc = "usdc",
    usde = "usde",
    usdp = "usdp",
    rlusd = "rlusd"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export type NFTTransferResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} | {
    __kind__: "alreadyListed";
    alreadyListed: null;
};
export type BuyNFTResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "notListed";
    notListed: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "cannotBuyOwn";
    cannotBuyOwn: null;
} | {
    __kind__: "insufficientFunds";
    insufficientFunds: null;
};
export interface NFTListing {
    tokenId: bigint;
    seller: Principal;
    priceE8s: bigint;
    listedAt: bigint;
    title: string;
    description: string;
    fileType: { audio: null } | { image: null } | { combined: null };
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAudiusTrackToPlaylist(playlistId: string, track: AudiusTrack): Promise<void>;
    addTrackToAlbum(albumId: string, trackId: string): Promise<void>;
    addTrackToPlaylist(playlistId: string, trackId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAlbum(input: AlbumInput): Promise<AlbumView>;
    createPlaylist(id: string, title: string): Promise<PlaylistView>;
    deleteAlbum(id: string): Promise<void>;
    deleteAudioFile(id: string): Promise<void>;
    deletePlaylist(id: string): Promise<void>;
    getAlbum(id: string): Promise<AlbumView | null>;
    getAllAudioFiles(): Promise<Array<AudioFile>>;
    getAllNFTRecords(): Promise<Array<NFTRecord>>;
    getAllNFTRecordsWithParams(): Promise<Array<NFTRecordWithParams>>;
    getAllPlaylists(): Promise<Array<PlaylistView>>;
    getAudioFile(id: string): Promise<AudioFile | null>;
    getAudioFilesByAlbum(albumId: string): Promise<Array<AudioFile>>;
    getCallerAudioFiles(): Promise<Array<AudioFile>>;
    getCallerNFTRecordsWithParams(): Promise<Array<NFTRecordWithParams>>;
    getCallerPlaylists(): Promise<Array<PlaylistView>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCanisterId(): Promise<Principal>;
    getNFTRecord(nftId: bigint): Promise<NFTRecord | null>;
    getNFTRecordWithParams(nftId: bigint): Promise<NFTRecordWithParams | null>;
    getPlaylist(id: string): Promise<PlaylistView | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAlbums(): Promise<Array<AlbumView>>;
    mintNFT(request: MintNFTRequest): Promise<MintNFTResponse>;
    mintNFTwithParams(request: MintNFTWithParamsRequest): Promise<MintNFTResponse>;
    removeAudiusTrackFromPlaylist(playlistId: string, trackId: string): Promise<void>;
    removeTrackFromPlaylist(playlistId: string, trackId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAlbum(id: string, input: AlbumInput): Promise<AlbumView>;
    updatePlaylistTitle(id: string, newTitle: string): Promise<void>;
    uploadAudioFile(file: AudioFile): Promise<string>;
    uploadTrackWithAlbum(file: AudioFile, albumId: string | null): Promise<string>;
    getListings(): Promise<Array<NFTListing>>;
    listNFTForSale(tokenId: bigint, priceE8s: bigint): Promise<NFTTransferResult>;
    delistNFT(tokenId: bigint): Promise<NFTTransferResult>;
    buyNFT(tokenId: bigint): Promise<BuyNFTResult>;
    ownerOf(tokenId: bigint): Promise<Principal | null>;
    transferNFT(tokenId: bigint, to: Principal): Promise<NFTTransferResult>;
}
import type { AlbumView as _AlbumView, AudioFile as _AudioFile, ExternalBlob as _ExternalBlob, FileType as _FileType, Genre as _Genre, MintNFTRequest as _MintNFTRequest, MintNFTResponse as _MintNFTResponse, MintNFTWithParamsRequest as _MintNFTWithParamsRequest, NFTMetadata as _NFTMetadata, NFTParameters as _NFTParameters, NFTRecord as _NFTRecord, NFTRecordWithParams as _NFTRecordWithParams, PlaylistView as _PlaylistView, RevenueSplit as _RevenueSplit, StableCoin as _StableCoin, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAudiusTrackToPlaylist(arg0: string, arg1: AudiusTrack): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAudiusTrackToPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAudiusTrackToPlaylist(arg0, arg1);
            return result;
        }
    }
    async addTrackToAlbum(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrackToAlbum(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrackToAlbum(arg0, arg1);
            return result;
        }
    }
    async addTrackToPlaylist(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrackToPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrackToPlaylist(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAlbum(arg0: AlbumInput): Promise<AlbumView> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlbum(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlbum(arg0);
            return result;
        }
    }
    async createPlaylist(arg0: string, arg1: string): Promise<PlaylistView> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlaylist(arg0, arg1);
            return result;
        }
    }
    async deleteAlbum(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlbum(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlbum(arg0);
            return result;
        }
    }
    async deleteAudioFile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAudioFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAudioFile(arg0);
            return result;
        }
    }
    async deletePlaylist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlaylist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlaylist(arg0);
            return result;
        }
    }
    async getAlbum(arg0: string): Promise<AlbumView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlbum(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlbum(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAudioFiles(): Promise<Array<AudioFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAudioFiles();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAudioFiles();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNFTRecords(): Promise<Array<NFTRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNFTRecords();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNFTRecords();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNFTRecordsWithParams(): Promise<Array<NFTRecordWithParams>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNFTRecordsWithParams();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNFTRecordsWithParams();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlaylists(): Promise<Array<PlaylistView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlaylists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlaylists();
            return result;
        }
    }
    async getAudioFile(arg0: string): Promise<AudioFile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAudioFile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAudioFile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAudioFilesByAlbum(arg0: string): Promise<Array<AudioFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAudioFilesByAlbum(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAudioFilesByAlbum(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAudioFiles(): Promise<Array<AudioFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAudioFiles();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAudioFiles();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerNFTRecordsWithParams(): Promise<Array<NFTRecordWithParams>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerNFTRecordsWithParams();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerNFTRecordsWithParams();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPlaylists(): Promise<Array<PlaylistView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPlaylists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPlaylists();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanisterId(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterId();
            return result;
        }
    }
    async getNFTRecord(arg0: bigint): Promise<NFTRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNFTRecord(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNFTRecord(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNFTRecordWithParams(arg0: bigint): Promise<NFTRecordWithParams | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNFTRecordWithParams(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNFTRecordWithParams(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlaylist(arg0: string): Promise<PlaylistView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaylist(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaylist(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAlbums(): Promise<Array<AlbumView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAlbums();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAlbums();
            return result;
        }
    }
    async mintNFT(arg0: MintNFTRequest): Promise<MintNFTResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.mintNFT(await to_candid_MintNFTRequest_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MintNFTResponse_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintNFT(await to_candid_MintNFTRequest_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MintNFTResponse_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async mintNFTwithParams(arg0: MintNFTWithParamsRequest): Promise<MintNFTResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.mintNFTwithParams(await to_candid_MintNFTWithParamsRequest_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MintNFTResponse_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintNFTwithParams(await to_candid_MintNFTWithParamsRequest_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MintNFTResponse_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeAudiusTrackFromPlaylist(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAudiusTrackFromPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAudiusTrackFromPlaylist(arg0, arg1);
            return result;
        }
    }
    async removeTrackFromPlaylist(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTrackFromPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTrackFromPlaylist(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n56(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAlbum(arg0: string, arg1: AlbumInput): Promise<AlbumView> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAlbum(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAlbum(arg0, arg1);
            return result;
        }
    }
    async updatePlaylistTitle(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlaylistTitle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlaylistTitle(arg0, arg1);
            return result;
        }
    }
    async uploadAudioFile(arg0: AudioFile): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadAudioFile(await to_candid_AudioFile_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadAudioFile(await to_candid_AudioFile_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadTrackWithAlbum(arg0: AudioFile, arg1: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadTrackWithAlbum(await to_candid_AudioFile_n58(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n62(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadTrackWithAlbum(await to_candid_AudioFile_n58(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n62(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getListings(): Promise<Array<NFTListing>> {
        return (this.actor as any).getListings();
    }
    async listNFTForSale(tokenId: bigint, priceE8s: bigint): Promise<NFTTransferResult> {
        return (this.actor as any).listNFTForSale(tokenId, priceE8s);
    }
    async delistNFT(tokenId: bigint): Promise<NFTTransferResult> {
        return (this.actor as any).delistNFT(tokenId);
    }
    async buyNFT(tokenId: bigint): Promise<BuyNFTResult> {
        return (this.actor as any).buyNFT(tokenId);
    }
    async ownerOf(tokenId: bigint): Promise<Principal | null> {
        return (this.actor as any).ownerOf(tokenId);
    }
    async transferNFT(tokenId: bigint, to: Principal): Promise<NFTTransferResult> {
        return (this.actor as any).transferNFT(tokenId, to);
    }
}
async function from_candid_AudioFile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioFile): Promise<AudioFile> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FileType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileType): FileType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Genre_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Genre): Genre {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_MintNFTResponse_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MintNFTResponse): MintNFTResponse {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_NFTMetadata_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NFTMetadata): NFTMetadata {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_NFTParameters_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NFTParameters): NFTParameters {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_NFTRecordWithParams_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NFTRecordWithParams): Promise<NFTRecordWithParams> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_NFTRecord_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NFTRecord): Promise<NFTRecord> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_StableCoin_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StableCoin): StableCoin {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AlbumView]): AlbumView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AudioFile]): Promise<AudioFile | null> {
    return value.length === 0 ? null : await from_candid_AudioFile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n36(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NFTRecord]): Promise<NFTRecord | null> {
    return value.length === 0 ? null : await from_candid_NFTRecord_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NFTRecordWithParams]): Promise<NFTRecordWithParams | null> {
    return value.length === 0 ? null : await from_candid_NFTRecordWithParams_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlaylistView]): PlaylistView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    creator: string;
    duration: bigint;
    owner: [] | [Principal];
    blob: _ExternalBlob;
    size: bigint;
    uploadTimestamp: bigint;
    coverImage: [] | [_ExternalBlob];
    genre: _Genre;
    albumId: [] | [string];
    isPublic: boolean;
}): Promise<{
    id: string;
    title: string;
    creator: string;
    duration: bigint;
    owner?: Principal;
    blob: ExternalBlob;
    size: bigint;
    uploadTimestamp: bigint;
    coverImage?: ExternalBlob;
    genre: Genre;
    albumId?: string;
    isPublic: boolean;
}> {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        duration: value.duration,
        owner: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.owner)),
        blob: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.blob),
        size: value.size,
        uploadTimestamp: value.uploadTimestamp,
        coverImage: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.coverImage)),
        genre: from_candid_Genre_n17(_uploadFile, _downloadFile, value.genre),
        albumId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.albumId)),
        isPublic: value.isPublic
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageBlob: [] | [_ExternalBlob];
    metadata: _NFTMetadata;
    audioBlob: [] | [_ExternalBlob];
}): Promise<{
    imageBlob?: ExternalBlob;
    metadata: NFTMetadata;
    audioBlob?: ExternalBlob;
}> {
    return {
        imageBlob: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.imageBlob)),
        metadata: from_candid_NFTMetadata_n23(_uploadFile, _downloadFile, value.metadata),
        audioBlob: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.audioBlob))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    owner: Principal;
    description: string;
    fileType: _FileType;
    originalContentId: string;
    mintTimestamp: bigint;
    artist: string;
}): {
    title: string;
    owner: Principal;
    description: string;
    fileType: FileType;
    originalContentId: string;
    mintTimestamp: bigint;
    artist: string;
} {
    return {
        title: value.title,
        owner: value.owner,
        description: value.description,
        fileType: from_candid_FileType_n25(_uploadFile, _downloadFile, value.fileType),
        originalContentId: value.originalContentId,
        mintTimestamp: value.mintTimestamp,
        artist: value.artist
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageBlob: [] | [_ExternalBlob];
    metadata: _NFTMetadata;
    audioBlob: [] | [_ExternalBlob];
    params: _NFTParameters;
}): Promise<{
    imageBlob?: ExternalBlob;
    metadata: NFTMetadata;
    audioBlob?: ExternalBlob;
    params: NFTParameters;
}> {
    return {
        imageBlob: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.imageBlob)),
        metadata: from_candid_NFTMetadata_n23(_uploadFile, _downloadFile, value.metadata),
        audioBlob: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.audioBlob)),
        params: from_candid_NFTParameters_n30(_uploadFile, _downloadFile, value.params)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stableCoin: _StableCoin;
    revenueSplits: Array<_RevenueSplit>;
    price: bigint;
    royaltyPercentage: bigint;
}): {
    stableCoin: StableCoin;
    revenueSplits: Array<RevenueSplit>;
    price: bigint;
    royaltyPercentage: bigint;
} {
    return {
        stableCoin: from_candid_StableCoin_n32(_uploadFile, _downloadFile, value.stableCoin),
        revenueSplits: value.revenueSplits,
        price: value.price,
        royaltyPercentage: value.royaltyPercentage
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    name: string;
    email: [] | [string];
}): {
    bio?: string;
    name: string;
    email?: string;
} {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.bio)),
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pop: null;
} | {
    other: string;
} | {
    jazz: null;
} | {
    rock: null;
} | {
    hipHop: null;
} | {
    electronic: null;
} | {
    classical: null;
}): {
    __kind__: "pop";
    pop: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "jazz";
    jazz: null;
} | {
    __kind__: "rock";
    rock: null;
} | {
    __kind__: "hipHop";
    hipHop: null;
} | {
    __kind__: "electronic";
    electronic: null;
} | {
    __kind__: "classical";
    classical: null;
} {
    return "pop" in value ? {
        __kind__: "pop",
        pop: value.pop
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "jazz" in value ? {
        __kind__: "jazz",
        jazz: value.jazz
    } : "rock" in value ? {
        __kind__: "rock",
        rock: value.rock
    } : "hipHop" in value ? {
        __kind__: "hipHop",
        hipHop: value.hipHop
    } : "electronic" in value ? {
        __kind__: "electronic",
        electronic: value.electronic
    } : "classical" in value ? {
        __kind__: "classical",
        classical: value.classical
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    audio: null;
} | {
    combined: null;
} | {
    image: null;
}): FileType {
    return "audio" in value ? FileType.audio : "combined" in value ? FileType.combined : "image" in value ? FileType.image : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tusd: null;
} | {
    usdc: null;
} | {
    usde: null;
} | {
    usdp: null;
} | {
    rlusd: null;
}): StableCoin {
    return "tusd" in value ? StableCoin.tusd : "usdc" in value ? StableCoin.usdc : "usde" in value ? StableCoin.usde : "usdp" in value ? StableCoin.usdp : "rlusd" in value ? StableCoin.rlusd : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    invalidInput: string;
} | {
    unauthorized: null;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
async function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AudioFile>): Promise<Array<AudioFile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AudioFile_n12(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NFTRecord>): Promise<Array<NFTRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_NFTRecord_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NFTRecordWithParams>): Promise<Array<NFTRecordWithParams>> {
    return await Promise.all(value.map(async (x)=>await from_candid_NFTRecordWithParams_n28(_uploadFile, _downloadFile, x)));
}
async function to_candid_AudioFile_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioFile): Promise<_AudioFile> {
    return await to_candid_record_n59(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FileType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): _FileType {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_Genre_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Genre): _Genre {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
async function to_candid_MintNFTRequest_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MintNFTRequest): Promise<_MintNFTRequest> {
    return await to_candid_record_n44(_uploadFile, _downloadFile, value);
}
async function to_candid_MintNFTWithParamsRequest_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MintNFTWithParamsRequest): Promise<_MintNFTWithParamsRequest> {
    return await to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_NFTParameters_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NFTParameters): _NFTParameters {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_StableCoin_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StableCoin): _StableCoin {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    imageBlob?: ExternalBlob;
    description: string;
    audioBlob?: ExternalBlob;
    fileType: FileType;
    originalContentId?: string;
    artist: string;
}): Promise<{
    title: string;
    imageBlob: [] | [_ExternalBlob];
    description: string;
    audioBlob: [] | [_ExternalBlob];
    fileType: _FileType;
    originalContentId: [] | [string];
    artist: string;
}> {
    return {
        title: value.title,
        imageBlob: value.imageBlob ? candid_some(await to_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.imageBlob)) : candid_none(),
        description: value.description,
        audioBlob: value.audioBlob ? candid_some(await to_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.audioBlob)) : candid_none(),
        fileType: to_candid_FileType_n46(_uploadFile, _downloadFile, value.fileType),
        originalContentId: value.originalContentId ? candid_some(value.originalContentId) : candid_none(),
        artist: value.artist
    };
}
async function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    imageBlob?: ExternalBlob;
    description: string;
    audioBlob?: ExternalBlob;
    fileType: FileType;
    originalContentId?: string;
    artist: string;
    params: NFTParameters;
}): Promise<{
    title: string;
    imageBlob: [] | [_ExternalBlob];
    description: string;
    audioBlob: [] | [_ExternalBlob];
    fileType: _FileType;
    originalContentId: [] | [string];
    artist: string;
    params: _NFTParameters;
}> {
    return {
        title: value.title,
        imageBlob: value.imageBlob ? candid_some(await to_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.imageBlob)) : candid_none(),
        description: value.description,
        audioBlob: value.audioBlob ? candid_some(await to_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.audioBlob)) : candid_none(),
        fileType: to_candid_FileType_n46(_uploadFile, _downloadFile, value.fileType),
        originalContentId: value.originalContentId ? candid_some(value.originalContentId) : candid_none(),
        artist: value.artist,
        params: to_candid_NFTParameters_n52(_uploadFile, _downloadFile, value.params)
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stableCoin: StableCoin;
    revenueSplits: Array<RevenueSplit>;
    price: bigint;
    royaltyPercentage: bigint;
}): {
    stableCoin: _StableCoin;
    revenueSplits: Array<_RevenueSplit>;
    price: bigint;
    royaltyPercentage: bigint;
} {
    return {
        stableCoin: to_candid_StableCoin_n54(_uploadFile, _downloadFile, value.stableCoin),
        revenueSplits: value.revenueSplits,
        price: value.price,
        royaltyPercentage: value.royaltyPercentage
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    name: string;
    email?: string;
}): {
    bio: [] | [string];
    name: string;
    email: [] | [string];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
async function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    creator: string;
    duration: bigint;
    owner?: Principal;
    blob: ExternalBlob;
    size: bigint;
    uploadTimestamp: bigint;
    coverImage?: ExternalBlob;
    genre: Genre;
    albumId?: string;
    isPublic: boolean;
}): Promise<{
    id: string;
    title: string;
    creator: string;
    duration: bigint;
    owner: [] | [Principal];
    blob: _ExternalBlob;
    size: bigint;
    uploadTimestamp: bigint;
    coverImage: [] | [_ExternalBlob];
    genre: _Genre;
    albumId: [] | [string];
    isPublic: boolean;
}> {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        duration: value.duration,
        owner: value.owner ? candid_some(value.owner) : candid_none(),
        blob: await to_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.blob),
        size: value.size,
        uploadTimestamp: value.uploadTimestamp,
        coverImage: value.coverImage ? candid_some(await to_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.coverImage)) : candid_none(),
        genre: to_candid_Genre_n60(_uploadFile, _downloadFile, value.genre),
        albumId: value.albumId ? candid_some(value.albumId) : candid_none(),
        isPublic: value.isPublic
    };
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): {
    audio: null;
} | {
    combined: null;
} | {
    image: null;
} {
    return value == FileType.audio ? {
        audio: null
    } : value == FileType.combined ? {
        combined: null
    } : value == FileType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StableCoin): {
    tusd: null;
} | {
    usdc: null;
} | {
    usde: null;
} | {
    usdp: null;
} | {
    rlusd: null;
} {
    return value == StableCoin.tusd ? {
        tusd: null
    } : value == StableCoin.usdc ? {
        usdc: null
    } : value == StableCoin.usde ? {
        usde: null
    } : value == StableCoin.usdp ? {
        usdp: null
    } : value == StableCoin.rlusd ? {
        rlusd: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "pop";
    pop: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "jazz";
    jazz: null;
} | {
    __kind__: "rock";
    rock: null;
} | {
    __kind__: "hipHop";
    hipHop: null;
} | {
    __kind__: "electronic";
    electronic: null;
} | {
    __kind__: "classical";
    classical: null;
}): {
    pop: null;
} | {
    other: string;
} | {
    jazz: null;
} | {
    rock: null;
} | {
    hipHop: null;
} | {
    electronic: null;
} | {
    classical: null;
} {
    return value.__kind__ === "pop" ? {
        pop: value.pop
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "jazz" ? {
        jazz: value.jazz
    } : value.__kind__ === "rock" ? {
        rock: value.rock
    } : value.__kind__ === "hipHop" ? {
        hipHop: value.hipHop
    } : value.__kind__ === "electronic" ? {
        electronic: value.electronic
    } : value.__kind__ === "classical" ? {
        classical: value.classical
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
